### ISSUE TITLE
/stop not working

### ISSUE THREAD

**Issue by babico** [L0SER8228/discord-player-bot#57]
**Describe the bug**
stop command not work

**To Reproduce**
1. Play any song
2. Stop while playing song
3. See error on log channel

**Error log**
TypeError: queue.node.delete is not a function
    at Object.execute (xxxxx/discord-player-bot/src/commands/music/stop.js:6:22)
    at execute (xxxxx/discord-player-bot/src/events/interactions/interactionCreate.js:87:23)
    at Client.emit (node:events:527:28)
    at InteractionCreateAction.handle (xxxxx/discord-player-bot/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at Object.module.exports [as INTERACTION_CREATE] (xxxxx/discord-player-bot/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (xxxxx/discord-player-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:354:31)
    at WebSocketManager.<anonymous> (xxxxx/discord-player-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:238:12)
    at WebSocketManager.emit (xxxxx/discord-player-bot/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
    at WebSocketShard.<anonymous> (xxxxx/discord-player-bot/node_modules/@discordjs/ws/dist/index.js:1103:51)
    at WebSocketShard.emit (xxxxx/discord-player-bot/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)

**Comment by L0SER8228** [comment]
Commit f1d818a should slove this issue

**Comment by L0SER8228** [comment]
Check all the commands. If you find any problem, feel free to open an issue again .

**Comment by babico** [comment]
> Check all the commands. If you find any problem, feel free to open an issue again .

Thanks mate.
